[versions]
kotlin = "2.4.10"
agp = "9.3.1"
foojay = "1.0.0"
coroutines = "1.10.1"
serialization = "1.8.0"
vanniktech = "0.37.0"
imgui-kmp = "1.0.8"
lsp-kmp = "1.0.0"
sdl-kmp = "1.0.7"
junit = "5.11.0"
junit-platform = "1.11.0"

[libraries]
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }
imgui-kmp = { module = "cn.enaium.imgui:imgui-kmp", version.ref = "imgui-kmp" }
lsp-kmp = { module = "cn.enaium:lsp-kmp", version.ref = "lsp-kmp" }
sdl-kmp = { module = "cn.enaium.sdl:sdl-kmp", version.ref = "sdl-kmp" }
junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junit" }
junit-platform-launcher = { group = "org.junit.platform", name = "junit-platform-launcher", version.ref = "junit-platform" }

[plugins]
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
android-kmp = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
foojay-resolver = { id = "org.gradle.toolchains.foojay-resolver-convention", version.ref = "foojay" }
maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "vanniktech" }